export const ProgressEnum = {
    STEP_1: "STEP_1",
    STEP_2_SUBSTEP_1: "STEP_2_SUBSTEP_1",
    STEP_2_SUBSTEP_2: "STEP_2_SUBSTEP_2",
    STEP_2_SUBSTEP_3: "STEP_2_SUBSTEP_3",
    STEP_3_SUBSTEP_1: "STEP_3_SUBSTEP_1",
    STEP_3_SUBSTEP_2: "STEP_3_SUBSTEP_2",
    STEP_3_SUBSTEP_3: "STEP_3_SUBSTEP_3",
};
